# Generated by Django 5.0.7 on 2024-07-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_message_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="subject",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="users.profile"
            ),
        ),
    ]
